# Generated by Django 4.2.1 on 2023-07-19 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0002_rename_encryption_algorithm_encryption_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryption',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
